NLRFIM-79 Support for reading OIOSAML3 privilege assertion based on profile version 1.0.2
digst/OIOIDWS.Net pull request #12
Opened 2021-02-10 12:57 UTC by thj-dk

2021-02-10 13:01 UTC, thj-dk commented on Source/Digst.OioIdws.Wsp/BasicPrivilegeProfile/BasicPrivilegeProfileSchema_v102.xsd
> +<?xml version="1.0" encoding="UTF-8"?>
XSD filerne bruges ikke, men jeg inkluderede den for dokumentationens skyld. Jeg er usikker på om det ønskes, eller om vi blot skal linke til specifikationen.

2021-02-10 13:06 UTC, sihpe commented on Source/Digst.OioIdws.Wsp/BasicPrivilegeProfile/BasicPrivilegeProfileDeserializer.cs
> +            var navtigator = doc.CreateNavigator();
`navtigator` -> `navigator`

2021-02-11 07:22 UTC, mdbech requested changes

2021-02-11 07:22 UTC, mdbech commented on Source/Digst.OioIdws.Wsp/BasicPrivilegeProfile/BasicPrivilegeProfileDeserializer.cs
> +        /// Deserializes a base64 encoded privilege assertion according to OIOSAML Basic Privilege Profile 1.0.1 or 1.0.2.
Er versionerne ikke 1.1 og 1.2?

2021-02-11 07:22 UTC, mdbech commented on Source/Digst.OioIdws.Wsp/BasicPrivilegeProfile/BasicPrivilegeProfileDeserializer.cs
> +        /// Deserializes a base64 encoded privilege assertion according to OIOSAML Basic Privilege Profile 1.0.1 or 1.0.2.
Det er det - det vil jeg gerne have rettet op på.

2021-02-11 07:31 UTC, thj-dk commented on Source/Digst.OioIdws.Wsp/BasicPrivilegeProfile/BasicPrivilegeProfileDeserializer.cs
> +        /// Deserializes a base64 encoded privilege assertion according to OIOSAML Basic Privilege Profile 1.0.1 or 1.0.2.
Versionen var 1.0.1, og så blev 1.2 tilføjet. Det har jeg rettet.

2021-02-11 09:11 UTC, mdbech approved these changes

2021-02-11 13:59 UTC, merged